#pragma once
#include <TugBoat/Core.h>
#define ENGINE_NAME "TugBoat"

#define ENGINE_VERSION_MAJOR 0
#define ENGINE_VERSION_MINOR 0
#define ENGINE_VERSION_PATCH 1

#define ENGINE_VERSION ((Version){ENGINE_VERSION_MAJOR, ENGINE_VERSION_MINOR, ENGINE_VERSION_PATCH});
